# Generated by Django 3.1.13 on 2023-02-22 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0002_auto_20230110_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='points',
            name='nomavatar',
            field=models.TextField(blank=True, null=True),
        ),
    ]
