# Generated by Django 3.1.13 on 2023-02-23 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(choices=[('1', 'Lundi'), ('2', 'Mardi'), ('3', 'Mercredi'), ('4', 'Jeudi'), ('5', 'Vendredi'), ('6', 'Samedi'), ('7', 'Dimanche')], max_length=1)),
                ('periode', models.CharField(choices=[('1', 'Matin'), ('2', 'Midi'), ('3', 'Aprem'), ('4', 'Soir')], max_length=1)),
                ('horaires', models.TextField()),
                ('nom', models.TextField()),
            ],
        ),
    ]
