# Generated by Django 3.1.13 on 2023-02-26 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='histodinos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defi', models.IntegerField()),
                ('montant', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('beneficaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benf', to=settings.AUTH_USER_MODEL)),
                ('payeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
