# Generated by Django 3.1.13 on 2023-02-27 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('histodefis', '0002_auto_20230227_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='histodinos',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
