# Generated by Django 3.1.13 on 2023-02-27 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('histodefis', '0003_auto_20230227_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='histodinos',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
