apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jura7-data
  namespace: jura7
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 2Gi
