# Generated by Django 3.1.13 on 2023-02-23 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='jour',
            field=models.CharField(choices=[('6', 'Samedi'), ('7', 'Dimanche'), ('1', 'Lundi'), ('2', 'Mardi'), ('3', 'Mercredi'), ('4', 'Jeudi'), ('5', 'Vendredi')], max_length=1),
        ),
    ]
