# Generated by Django 3.1.13 on 2023-02-23 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paris', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paris',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
