# Generated by Django 3.1.13 on 2023-03-02 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paris', '0002_paris_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='paris',
            name='numero',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
