# Generated by Django 3.1.13 on 2023-01-09 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcodes', '0002_auto_20230109_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeqr',
            name='utilisateur',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
