# Generated by Django 3.1.13 on 2023-01-17 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcodes', '0003_auto_20230109_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeqr',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
