# Generated by Django 3.1.13 on 2023-01-19 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qrcodes', '0005_auto_20230119_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeqr',
            name='createur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creat_codeqr', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='codeqr',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_codeqr', to=settings.AUTH_USER_MODEL),
        ),
    ]
