# Generated by Django 3.1.13 on 2023-02-20 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcodes', '0006_auto_20230119_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeqr',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
