# Generated by Django 3.1.13 on 2023-02-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcodes', '0007_codeqr_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeqr',
            name='lien',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
