# Generated by Django 3.1.13 on 2023-02-23 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcodes', '0008_codeqr_lien'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codeqr',
            name='is_public',
        ),
        migrations.AddField(
            model_name='codeqr',
            name='nb_utilisation',
            field=models.IntegerField(default=1),
        ),
    ]
