# Generated by Django 3.1.13 on 2023-02-24 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='')),
                ('stock', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
