# Generated by Django 3.1.13 on 2023-02-18 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enigmes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enigme',
            name='numero_enigme',
            field=models.IntegerField(),
        ),
    ]
