# Generated by Django 3.1.13 on 2023-02-22 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='repenigmes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_enigme', models.IntegerField()),
                ('reponse', models.CharField(max_length=200)),
            ],
        ),
    ]
