# Generated by Django 3.1.13 on 2023-02-23 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repenigmes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repenigmes',
            name='indice',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='repenigmes',
            name='numero_enigme',
            field=models.CharField(choices=[('3', 'Lundi'), ('4', 'Mardi'), ('5', 'Mercredi'), ('6', 'Jeudi'), ('7', 'Vendredi'), ('1', 'Samedi'), ('2', 'Dimanche')], max_length=1),
        ),
    ]
